version: "3.8"                                          # 파일 규격 버전
services:                                               # 이 항목 밑에 실행하려는 컨테이너들을 정의
  pharmacy-recommendation-redis:                        # 서비스명
    container_name:        # 컨테이너명
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: 31f08b90668e/redis
    ports:
      - "6379:6379"
  cool_goldberg:
    container_name: cool_goldberg
    build:
      dockerfile: Dockerfile
      context: ./database
    image: e4761f748bf5/spring
    environment:
      - MARIADB_DATABASE=findingshelter
      - MARIADB_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./database/config:/etc/mysql/conf.d
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"      # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)
